<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['irw_myreviews'] = array(
    'table' => 'irw_myreviews',
    'audited' => true,
    'inline_edit' => true,
    'fields' => array (
      'irw_myreviews_list' =>
      array (
        'required' => true,
        'name' => 'irw_myreviews_list',
        'vname' => 'LBL_IRW_MYREVIEWS_LIST',
        'type' => 'enum',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => 'Como se clasifica la ACPM',
        'help' => 'Como se clasifica la ACPM',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 100,
        'size' => '20',
        'options' => 'irw_myreviews_list',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'detail' =>
      array (
        'required' => false,
        'name' => 'detail',
        'vname' => 'LBL_DETAIL',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '4',
        'cols' => '20',
      ),
      'irw_myreviews_source' =>
      array (
        'required' => true,
        'name' => 'irw_myreviews_source',
        'vname' => 'LBL_IRW_MYREVIEWS_SOURCE',
        'type' => 'enum',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 100,
        'size' => '20',
        'options' => 'irw_myreviews_source',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'irw_myreviews_status' =>
      array (
        'required' => true,
        'name' => 'irw_myreviews_status',
        'vname' => 'LBL_IRW_MYREVIEWS_STATUS',
        'type' => 'enum',
        'massupdate' => 0,
        'default' => 'process',
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 100,
        'size' => '20',
        'options' => 'irw_myreviews_status',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'irw_processes_id' =>
      array (
        'required' => false,
        'name' => 'irw_processes_id',
        'vname' => 'LBL_PROCESS_IRW_PROCESSES_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
      ),
      'process' =>
      array (
        'required' => true,
        'source' => 'non-db',
        'name' => 'process',
        'vname' => 'LBL_PROCESS',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'irw_processes_id',
        'ext2' => 'irw_processes',
        'module' => 'irw_processes',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
      ),
      'first' =>
      array (
        'required' => true,
        'name' => 'first',
        'vname' => 'LBL_FIRST',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '3',
        'cols' => '20',
      ),
      'second' =>
      array (
        'required' => true,
        'name' => 'second',
        'vname' => 'LBL_SECOND',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '3',
        'cols' => '20',
      ),
      'third' =>
      array (
        'required' => true,
        'name' => 'third',
        'vname' => 'LBL_THIRD',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '3',
        'cols' => '20',
      ),
      'fourth' =>
      array (
        'required' => true,
        'name' => 'fourth',
        'vname' => 'LBL_FOURTH',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '3',
        'cols' => '20',
      ),
      'fifth' =>
      array (
        'required' => true,
        'name' => 'fifth',
        'vname' => 'LBL_FIFTH',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '3',
        'cols' => '20',
      ),
      'root_cause' =>
      array (
        'required' => true,
        'name' => 'root_cause',
        'vname' => 'LBL_ROOT_CAUSE',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '3',
        'cols' => '20',
      ),
      'consecutive' =>
      array (
        'required' => false,
        'name' => 'consecutive',
        'vname' => 'LBL_CONSECUTIVE',
        'type' => 'int',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'enable_range_search' => false,
        'disable_num_format' => '1',
        'min' => false,
        'max' => false,
      ),
      'which_one' =>
      array (
        'required' => false,
        'name' => 'which_one',
        'vname' => 'LBL_WHICH_ONE',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
      'closed' =>
      array (
        'required' => false,
        'name' => 'closed',
        'vname' => 'LBL_CLOSED',
        'type' => 'bool',
        'massupdate' => 0,
        'default' => '0',
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
      'date_closed' =>
      array (
        'required' => false,
        'name' => 'date_closed',
        'vname' => 'LBL_DATE_CLOSED',
        'type' => 'date',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'enable_range_search' => false,
      ),
      'closed_effectively' =>
      array (
        'required' => false,
        'name' => 'closed_effectively',
        'vname' => 'LBL_CLOSED_EFFECTIVELY',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '3',
        'cols' => '20',
      ),
      'irw_indicators_id' =>
      array (
        'required' => false,
        'name' => 'irw_indicators_id',
        'vname' => 'LBL_INDICATOR_IRW_INDICATORS_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => false,
        'inline_edit' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
      ),
      'indicator' =>
      array (
        'required' => false,
        'source' => 'non-db',
        'name' => 'indicator',
        'vname' => 'LBL_INDICATOR',
        'type' => 'relate',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'inline_edit' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'irw_indicators_id',
        'ext2' => 'irw_indicators',
        'module' => 'irw_indicators',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
      ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('irw_myreviews', 'irw_myreviews', array('basic','assignable','security_groups','file'));
